name: Zoo CI

on:
  push:
    branches:
      - main
  pull_request:
      - main

jobs:
  build-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build Docker image (runs make -j4 inside)
        run: docker build -t zoo-ci .
